/* eslint-disable react/no-unknown-property */
/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline';
import { OrthographicCamera } from '@react-three/drei';

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/KIClsoN4aLneStrR/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#74757a']} />
      <group {...props} dispose={null}>
        <scene name="Scene 1">
          <OrthographicCamera
            name="Camera"
            makeDefault={true}
            zoom={0.1}
            far={100000}
            near={-100000}
            up={[0, 1, 0]}
            position={[-1510.89, -239.71, 3482.65]}
            rotation={[-Math.PI / 4, 0.62, Math.PI / 6]}
          />
          <mesh
            name="Sphere"
            geometry={nodes.Sphere.geometry}
            material={materials['Sphere Material']}
            castShadow
            receiveShadow
            position={[31.36, 58.8, 0]}
            scale={3}
          />
          <directionalLight
            name="Directional Light"
            castShadow
            intensity={0.7}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-1000}
            shadow-camera-right={1000}
            shadow-camera-top={1000}
            shadow-camera-bottom={-1000}
            position={[337, 461, 300]}
          />
          <OrthographicCamera name="1" makeDefault={false} far={10000} near={-50000} />
          <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
        </scene>
      </group>
    </>
  )
}